services:

  sysagenda_back_api:
    image: sysagenda_back_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network_swarm_public
      - sysagenda-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_sysagenda
      SPRING_DATASOURCE_USERNAME: sysagenda
      SPRING_DATASOURCE_PASSWORD: Bh@scara
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      TZ: America/Sao_Paulo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=network_swarm_public"

        - "traefik.http.routers.sysagenda-api.rule=Host(`sistema.automica.com.br`)"
        - "traefik.http.routers.sysagenda-api.entrypoints=websecure"
        - "traefik.http.routers.sysagenda-api.tls=true"
        - "traefik.http.routers.sysagenda-api.tls.certresolver=letsencryptresolver"

        - "traefik.http.services.sysagenda-api.loadbalancer.server.port=8080"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: db_sysagenda
      POSTGRES_USER: sysagenda
      POSTGRES_PASSWORD: Bh@scara
      TZ: America/Sao_Paulo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sysagenda-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sysagenda -d db_sysagenda"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  network_swarm_public:
    external: true
  sysagenda-network:
    driver: overlay
    attachable: true

volumes:
  postgres_data:
